module Pages(
    module Pages.Mixer,
    module Pages.Bass,
    module Pages.Noiser,
    module Pages.Haunted,
    module Pages.Flow,
    module Pages.Synt,
    module Pages.PadList,
    module Pages.Loop,    
    module Pages.Spec
) where

import Pages.Mixer
import Pages.Bass
import Pages.Noiser
import Pages.Haunted
import Pages.Flow
import Pages.Synt
import Pages.PadList
import Pages.Loop
import Pages.Spec
